
def dreptunghi():
    import turtle
    t = turtle.Pen()
    t.shape('turtle')
    t.color('red')
    t.forward(200)
    t.left(90)
    t.forward(100)
    t.left(90)
    t.forward(200)
    t.left(90)
    t.forward(100)
    t.up()
    t.left(90)
    t.forward(50)
    t.left(90)
    t.forward(20)
    t.down()
    t.color('yellow')
    t.right(90)
    t.forward(50)
    t.left(90)
    t.forward(25)
    t.left(90)
    t.forward(50)
    t.left(90)
    t.forward(25)
    t.reset()
def herz():
    import turtle
    t = turtle.Pen()
    t.shape('turtle')
    t.color('red')
    t.left(140)
    t.forward(100)
    for i in range(200):
        t.right(1)
        t.forward(1)
    t.left(120)
    for i in range(200):
        t.right(1)
        t.forward(1)

    t.forward(100)
    t.reset()
def haus():
    import turtle
    t = turtle.Pen()
    c=t.clone()
    t.shape('turtle')
    c.shape('turtle')
    t.up()
    c.up()
    t.forward(50)
    c.backward(250)
    t.down()
    c.down()
    t.forward(200)
    c.forward(200)
    t.left(90)
    c.left(90)
    t.forward(100)
    c.forward(100)
    t.left(90)
    c.left(90)
    t.forward(200)
    c.forward(200)
    t.left(90)
    c.left(90)
    t.forward(100)
    c.forward(100)
    t.up()
    c.up()
    t.left(90)
    c.left(90)
    t.forward(50)
    c.forward(50)
    t.left(90)
    c.left(90)
    t.forward(100)
    c.forward(100)
    t.left(90)
    c.left(90)
    t.forward(50)
    c.forward(50)
    t.right(90)
    c.right(90)
    t.down()
    c.down()
    t.color('red')
    c.color('red')
    t.right(45)
    c.right(45)
    t.forward(150)
    c.forward(150)
    t.right(94)
    c.right(94)
    t.forward(150)
    c.forward(150)
    t.up()
    c.up()
    t.right(140)
    c.right(140)
    t.forward(100)
    c.forward(100)
    t.left(90)
    c.left(90)
    t.forward(40)
    c.forward(40)
    t.right(90)
    c.right(90)
    t.left(90)
    c.left(90)
    t.left(99)
    c.left(99)
    t.down()
    c.down()
    t.color('yellow')
    c.color('yellow')

    t.forward(50)
    c.forward(50)
    t.left(90)
    c.left(90)
    t.forward(25)
    c.forward(25)
    t.left(90)
    c.left(90)
    t.forward(50)
    c.forward(50)
    t.left(90)
    c.left(90)
    t.forward(25)
    c.forward(25)
    t.up()
    c.up()
    t.forward(70)
    c.forward(70)
    t.right(180)
    c.right(180)
    t.down()
    c.down()
    t.color('brown')
    c.color('brown')
    t.forward(55)
    c.forward(55)
    t.left(90)
    c.left(90)
    t.forward(37)
    c.forward(37)
    t.left(90)
    c.left(90)
    t.forward(55)
    c.forward(55)
    t.reset()
    c.reset()

def menu():
    return """
        Wahlen sie ein Zeichnung:
        1-Rechteck
        2-Herz
        3-Haus
        """

def main():
    opt=(int)(input("Bitte wahlen:"))
    if opt==1:
        dreptunghi()
    if opt==2:
        herz()
    if opt==3:
        haus()



print(menu())
main()